SCREEN_WIDTH = 2560
SCREEN_HEIGHT = 1440
LINE_WIDTH = 3 

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 400
PLAYER_SPEED = 300
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3

SHOT_RADIUS = 5

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 5
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS